---
# variables required for sshtunneling
#   These variables can be used in one tunneling,
#   or they can be called by other roles, for example as in roles/mysql_repl, roles/mysql_dbmig
#   roles/mysql_dbmig for dbmigration and repl_vars for mysql replication.

# -----------------------------------------
# sshgate
# A special ssh user is set aside to use for setting up sshtunneling

# -----------------------------------------
# sshforwarding:
#   remote_server: 11.11.11.11
#   remote server whose port need to be mapped to local server

#   remote_port: 3306
#   port in remote server which need to be mapped to local port

#   local_port: 1111
#   Port in localhost which would receive the remote forwarding port_process
#   Below are our set library of local ports used for sshtunneling
#   dbmig_port: 4025

#   repl_port1: 6701
#   repl_port2: 6702
#   repl_port3: 6703
#   repl_port4: 6704
#   repl_port5: 6705
#   repl_port6: 6706
#   repl_port7: 6707
#   repl_port8: 6708
#   repl_port9: 6709

#   etl_port1: 4101
#   etl_port2: 4102
#   etl_port3: 4103
#   etl_port4: 4104
#   etl_port5: 4105
