---
# Basic server setup
# ===================================================================
# This ansible is to the first playbook to run after a server is spinned
# Tasks include:
#   1. common installs
#   2. add a ansible tower user
#   3. Some basic security configuration for sshd, firewalld and selinux
# the related variables is each group_vars
# ===================================================================

- name: set up database servers
  hosts: all
  become: true
  ignore_errors: yes
  vars_files:
    - group_vars/all.yml
  
  tasks:
    - name: run initial server setup, dnf-automatic for security update, chrony for time setting
      include_role:
        name: basic_server
        tasks_from: initiate.yml

    - name: Secure install mysql
      include_role:
        name: mysql
        tasks_from: install.yml

    - name: add server admin user
      include_role: 
        name: basic_server
        tasks_from: server_users.yml
    
    - name: server security implementation
      include_role: 
        name: basic_server
        tasks_from: security.yml

    - name: create database
      include_role:
        name: mysql
        tasks_from: databases.yml

    - name: create db users
      include_role:
        name: mysql
        tasks_from: db_users.yml
