---
# Basic server setup
# ===================================================================
# This ansible is to the first playbook to run after a server is spinned
# Tasks include:
#   1. common installs
#   2. add a ansible tower user
#   3. Some basic security configuration for sshd, firewalld and selinux
# the related variables is each group_vars
# ===================================================================

- name: a test playbook
  hosts: all
  become: true
  become_method: sudo
  ignore_errors: yes
  vars_files:
    - host_vars/dbServer.yml

  tasks:
  - name: Leaving a mark
    command: "touch /tmp/ansible_was_here"