---
# - name: Ensure MySQL databases are present.
#   mysql_db:
#     name: "{{ item.name }}"
#     collation: "{{ item.collation | default('utf8_general_ci') }}"
#     encoding: "{{ item.encoding | default('utf8') }}"
#     state: "{{ item.state | default('present') }}"
#   with_items: "{{ mysql_databases }}"

# ------------------create database ------------------------------

- name: Create databases
  mysql_db:
    name: "{{ item }}"
    encoding: utf8mb4   #utf8 is alias for utf8mb3 and is depreciated
    collation: utf8mb4_unicode_ci
    state: present
    login_user: "{{ db_rootuser_name }}"
    login_password: "{{ db_rootuser_password }}"
  with_items:
    - "{{ mrd_db }}"
  when: mrd_db|default('') != ''

# Collation: sort order, how characters are compared
# utf8mb4_bin: compares the binary value of characters, so it is case sensitive
# utf8mb4_unicode_ci: follows the Unicode standard for comparisons.
# utf8mb4_general_ci: faster but less correct than the unicode collation.


