---

# this code is to set the MySQL port aviliable.
# our ansible_os_family = RedHat

#--------- 1. Firewalld security configuration-----------------------

- name: remove default mysql port
  firewalld:
    service: mysql
    permanent: true
    state: disabled
  notify:
  - reload firewalld

# add the new mysql port
- name: open new mysql port, as described in group_vars or host_vars
  firewalld:
    port: "{{ mrd_ports.mysql }}/tcp"
    permanent: true
    state: enabled
  notify:
  - reload firewalld

# ----------2. Selinux security configurations--------------------------------
# turn on the 7878 port (mysqld) permission
- name: Open specified mysql port in selinux
  seport:
    ports: "{{ mrd_ports.mysql }}"
    proto: tcp
    setype: mysqld_port_t
    state: present

- name: Configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes

# -----------3. database connection via ssh tunneling------------------------
# xxxxxxxxxxxxxxxxxxx
