---
#============================================================================
# This role installs common programs to all servers after the server initiaion

# Before this, server was spinned with root user with sysadmin ssh key
# Details of each server capacity are in inventory/hosts
# Centos7 package came with centos7 base, centos-7 extras, centos7-updates
 # Can use yum repolist to check what is installed
 # Use yum repolist enabled for enabled repo

# Tasks in this role include:
#   1. update all the server packages in centos7 and install epel repo and yum utility
#   2. ntp and ntp configuration file installation
#   3. set timezone to shanghai
#   4. yum-cron and its config file installation
#
#  Related templates:
#   1. ntp.conf.j2
#   2. yum-cron.conf.j2

#===========================================================

# ---------------- Configure and install yum and its componets------------
# Update all the server packages ----------
- name: upgrade all packages for server
  yum:
    name: '*'
    state: latest

- name: install epel package manager and yum-utils
  yum:
    name:
      - epel-release         #EPEL provides only software that is not in the official CentOS and Red Hat repositories
      - yum-utils
    state: latest

# IUS provides newer versions of software (like MySQL and PHP) that exist in the official repositories.
# - name: install ius repos as Python3 source
#   yum:
#     pkg: https://centos7.iuscommunity.org/ius-release.rpm
#     state: present

# - name: install centos7 build tools to allow build and compile software from source code
#   yum:
#     name: "@Development tools"
#     state: present
#   become: yes

# ---------------- ntp installation and configuration ----------------
- name: Install ntp
  yum: name=ntp state=present

- name: Copy ntp configuration template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf

- name: Enable and start the ntp service
  service: name=ntpd state=started enabled=yes

# ---------------- set timezone ----------------
# https://docs.ansible.com/ansible/2.5/modules/timezone_module.html
- name: set timezone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai

# ---------------- Install yum-cron for automatic update ----------
- name: yum-cron installation
  yum:
    name: yum-cron
    state: installed

- name: Configure yum-cron.conf
  template: src=yum-cron.conf.j2 dest=/etc/yum/yum-cron.conf

- name: Enable and start yum-cron
  service: name=yum-cron state=started enabled=yes
